#!/usr/bin/env python3

import os
import shutil

os.chdir('3rd')
if os.name == 'posix':
    os.chdir('boost')
    os.system('git submodule update --init --recursive')
    os.system('./bootstrap.sh')
    os.system('./b2')
    os.chdir('..')
    os.chdir('freetype2')
    os.system('./autogen.sh')
    os.system('./configure')
    os.system('./make')
    os.chdir('..')
    os.chdir('glew/auto')
    os.system('make')
    os.chdir('..')
    os.system('make')
    os.chdir('..')
    os.chdir('glfw')
    os.system('mkdir build')
    os.chdir('build')
    os.system('cmake -DCMAKE_BUILD_TYPE=Release ..')
    os.system('make')
    os.chdir('../..')
    # os.chdir('libjpeg-turbo')
    # os.system('mkdir build')
    # os.chdir('build')
    # os.system('cmake -DCMAKE_BUILD_TYPE=Release ..')
    # os.system('make')
    os.chdir('libpng')
    os.system('./autogen.sh')
    os.system('./configure')
    os.system('./make')
    os.chdir('..')
    os.chdir('ogg')
    os.system('mkdir build')
    os.chdir('build')
    os.system('cmake -DCMAKE_BUILD_TYPE=Release ..')
    os.system('make')
    os.chdir('../..')
    os.chdir('oniguruma')
    os.system('./autogen.sh')
    os.system('./configure')
    os.system('./make')
    os.chdir('..')
    os.chdir('openalsoft/build')
    os.system('cmake -DCMAKE_BUILD_TYPE=Release ..')
    os.system('make')
    os.chdir('../..')
    os.chdir('openssl')
    os.system('./config')
    os.system('make')
    os.chdir('..')
    os.chdir('rapidjson')
    os.system('mkdir build')
    os.chdir('build')
    os.system('cmake -DCMAKE_BUILD_TYPE=Release ..')
    os.system('make')
    os.chdir('../..')
    # os.chdir('sqlite')
    # os.system('./configure')
    # os.system('./make')
    # os.chdir('..')
