#!/usr/bin/env python3

import os
import shutil

def cmake_build():
    os.system('mkdir build')
    os.chdir('build')
    os.system('cmake -DCMAKE_BUILD_TYPE=Release ..')
    os.system('make')
    os.chdir('../..')

def auto_make():
    os.system('./autogen.sh')
    os.system('./configure')
    os.system('make')
    os.chdir('..')

os.chdir('3rd')
if os.name == 'posix':
    os.chdir('zlib')
    cmake_build()
    os.chdir('boost')
    os.system('git submodule update --init --recursive')
    os.system('./bootstrap.sh')
    os.system('./b2')
    os.chdir('..')
    os.chdir('ffmpeg')
    os.system('./configure')
    os.system('make')
    os.chdir('..')
    os.chdir('freetype2')
    auto_make()
    os.chdir('glew/auto')
    os.system('make')
    os.chdir('..')
    os.system('make')
    os.chdir('..')
    os.chdir('glfw')
    cmake_build()
    os.chdir('libjpeg-turbo')
    cmake_build()
    os.chdir('libpng')
    auto_make()
    os.chdir('ogg')
    auto_make()
    os.chdir('oniguruma')
    auto_make()
    os.chdir('openalsoft/build')
    os.system('cmake -DCMAKE_BUILD_TYPE=Release ..')
    os.system('make')
    os.chdir('../..')
    os.chdir('openssl')
    os.system('./config')
    os.system('make')
    os.chdir('..')
    os.chdir('rapidjson')
    cmake_build()
    os.chdir('sqlite')
    os.system('./configure')
    os.system('make')
    os.chdir('..')
    os.chdir('vorbis')
    auto_make()
    os.system('git clone https://chromium.googlesource.com/chromium/tools/depot_tools.git')
    os.environ["PATH"] += os.getcwd() + "/depot_tools"
    os.system('gclient')
    os.system('rm -rf v8')
    os.system('fetch v8')
    os.system('gclient sync')
    os.chdir('v8')
    os.system('sudo ./build/install-build-deps.sh')
    os.system('tools/dev/v8gen.py x64.release')
    os.system('ninja -C out.gn/x64.release')
    os.chdir('curl')
    os.system('autoreconf -vfi')
    os.system('./configure')
    os.system('make')
    os.chdir('..')
